title:        Montevideo
tagline:      'Montevideo'
description:  'Pathfinder in Markdown'
url:          http://brunokoga.com
version:      0.1
author:
  name:       'Bruno Koga'
  email:      'koga@brunokoga.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
